### ISSUE TITLE
Problem finding .temp files

### ISSUE THREAD

**Issue by lrverdon** [tinawunderlich/MultichannelGPR#1]
When following the Tutorial as part of the JOSS review (https://github.com/openjournals/joss-reviews/issues/6767), in different steps of the tutorial, I had problems with the .temp files which the system could not find, e.g. when running the scripts 'DZT_convert.m' (dzt.temp), 'processing.m', 'Radargrams2bins.m', 'make_timeslices.m' (temp.temp), 'saveFigures.m' (radtemp.temp). 
This occurred during different tests on different computers, but did not occur after I had removed a previous version of MultichannelGPR which had been in the Matlab Search Path. 
If more information is available on what may cause this (older version of MultichannelGPR in the search path?), it may be useful to mention this in the documentation to remind the users.

I ran the tests on PCs with Windows 10 Pro 64 bits, Version 22H2

**Comment by tinawunderlich** [comment]
Thank you for testing this. Unfortunately, this is an issue not easy to solve. The .temp-files are saved for remembering the last given folder so that when you run a script multiple times you do not need to click through the complete folder structure.
Normally I am working on a Mac, but at some point I was forced to use a Windows PC for programming. At this specific PC it occured that there was a problem with creating/reading these files as there seems to be a special thing on how to create hidden files. Unfortunately I cannot use that PC anymore. At that point I added the "if ispc..." part in the beginning when reading/creating the temp files. Obviously, some Windows versions have a problem with this. I'll think about this problem and how to solve it in the next few days.
There is already a small hint in the Troubleshooting-part of the Wiki, but maybe I should post it more pronounced, and also in the Tutorial.
I'll come back to this issue...

**Comment by tinawunderlich** [comment]
For me to better understand the problem, could you reproduce the error and post the error message? Thanks!

**Comment by lrverdon** [comment]
The errors which I got when MultichannelGPR_v1.1.3 was still in my Matlab Search Path were of the form (example when running 'Processing.m', step 5 of Tutorial):

Error using fileattrib
The system cannot find the file specified
Error in Processing (line 43)
        fileattrib('radtemp.temp','-h');

For later tests I have removed MultichannelGPR_v1.1.3, and I have not entered MultichannGPR_v1.2.4 in the Matlab Search Path, I just opened the scripts in the folder where they are stored, and ran them as indicated in the Tutorial. I no longer get the error above, but when going through the tutorial recently, I had the following error in two different steps of the tutorial:

1) When running the script 'Process_SingleProfile.m' (step 5). I got the error:

Error using matlab.ui.internal.dialog.FileSystemChooser/PathParser (line 87)
Invalid directory to operate on
Error in matlab.ui.internal.dialog.FileSystemChooser/set.InitialPathName (line 32)
                iPath = PathParser(obj,iPath);
Error in uigetdir_helper (line 36)
    dirdlg.InitialPathName = dialog_pathname;
Error in uigetdir (line 68)
[directoryname] = uigetdir_helper(varargin{:});
Error in Process_SingleProfile (line 27)
            folder=uigetdir(fn{1}{1},'Select data-folder');

I could avoid this by commenting out line 21-35 of the script, then the error below appeared:

Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.
Error in Process_SingleProfile (line 38)
        fprintf(fid,'%s',folder);

Also commenting out line 37-40 allowed selecting the 'setCoords' folder.

2) I got the same error when running 'saveFigures.m' (step 12)

Error using matlab.ui.internal.dialog.FileSystemChooser/PathParser (line 87)
Invalid directory to operate on
Error in matlab.ui.internal.dialog.FileSystemChooser/set.InitialPathName (line 32)
                iPath = PathParser(obj,iPath);
Error in uigetdir_helper (line 36)
    dirdlg.InitialPathName = dialog_pathname;
Error in uigetdir (line 68)
[directoryname] = uigetdir_helper(varargin{:});
Error in saveFigures (line 60)
            pfad_rad=uigetdir(fn{1}{1},'Choose folder with radargrams');

These two errors refer to lines in the scripts dealing with the .temp files, so I assume they are a related problem.

Perhaps one part of the solution to avoid errors in case anything goes wrong may be to build in an 'escape route'
when the system cannot find the temporary file or the value in the temporary file is wrong, for example in that case the current Matlab folder is given as default in the folder selection dialog.

**Comment by tinawunderlich** [comment]
Thank you very much for reproducing the error messages! I agree that the errors are relatde to the temp-files. I'll try to build an "escape-route" as you suggested, hoping that I can think of any possible problem that could occur ;-)

**Comment by tinawunderlich** [comment]
I changed now all scripts and for Windows the temporarily saved files are now not hidden (which was the main source of problems). If you still encounter problems with uigetfile/uigetdir there is a solution in the Wiki/Troubleshooting, which is also linked to the tutorial.
