### ISSUE TITLE
Problem when running isochrone migration in 'Process_SingleProfile' script

### ISSUE THREAD

**Issue by lrverdon** [tinawunderlich/MultichannelGPR#2]
When running 'Process_SingleProfile.m' (step 5 of the Tutorial) as part of the JOSS review (https://github.com/openjournals/joss-reviews/issues/6767), I could not get the isochrone migration to work on the basis of the description of the 'Process_SingleProfile' script in the tutorial and in the 'Scripts_for_2D' part  of the Wiki. 
I selected the .mat files with the time and the velocity (should these be vectors with length equal to the number of temporal samples in the profile?) but the function kept running without end or gave an error message like the one below:

Arrays have incompatible sizes for this operation.
Error in isochrone_mig_2d_varV (line 57)
    v=zeros(size(data))+v;
Error in processingTestGUI_mat>processing (line 1132)
        [datatemp,zmig]=isochrone_mig_2d_varV(datatraces,x,tp,vgrid,params.aperture,0);
Error in processingTestGUI_mat/apply_call (line 967)
        [S.proc,S.ns,S.tproc,S.zmig,S.f,S.ampl]=processing(steps,order,S.raw,S.xprof,S.xyz,S.t,params,S);
Error while evaluating UIControl Callback.
 
Perhaps it could be further clarified in the documentation how to use the isochrone migration in 'Process_SingleProfile.m'? When I ran the 'isochrone_mig_2d_varV' function manually on some test GPR data, it worked fine.
(tested on a PC with Windows 10 Pro 64 bits, Version 22H2)

**Comment by tinawunderlich** [comment]
Thank you for testing this! I have to admit that this is a function I seldom use. I'll have a look and fix it. Maybe I could limit the isochrone migration in the Process-SingleProfile to a constant velocity (as for the topomigration) as this would be much easier to use without the need to create the v.mat and vt.mat-files before. If a user wants to use a more complex velocity function this can be applied in the Processing.m. Do you think that this is sufficient for the Process_SingleProfile?

**Comment by lrverdon** [comment]
Yes, I think that would be sufficient. Then the user gets an impression of what the data looks like after migration (even if there are variations in the velocity, a good average will be a nice approximation). In case certain mat-files can be selected, it is useful to specify in the guidelines if they can/should be scalars, vectors or matrices with a certain size.

**Comment by tinawunderlich** [comment]
Ok, thanks. Then I'll implement it like that.

**Comment by tinawunderlich** [comment]
It is implemented in the GUI and Mala3D & MalaProcessing are adjusted to the settings-file from Process_SingleProfile. When you are using mat-files the required format is given in the Wiki.
